# -*- mode: python ; coding: utf-8 -*-
import sys
from pathlib import Path

block_cipher = None

a = Analysis(
    ['src/plc_tools/app.py'],
    pathex=[str(Path('src').resolve())],
    binaries=[],
    datas=[],
    hiddenimports=[
        'plc_tools',
        'plc_tools.app',
        'plc_tools.communication',
        'plc_tools.communication.models',
        'plc_tools.communication.base_driver',
        'plc_tools.communication.mock_driver',
        'plc_tools.communication.logix_driver',
        'plc_tools.communication.micro800_driver',
        'plc_tools.communication.network_scanner',
        'plc_tools.communication.l5x_parser',
        'plc_tools.communication.connection_manager',
        'plc_tools.communication.project_manager',
        'plc_tools.gui',
        'plc_tools.gui.main_window',
        'plc_tools.gui.connect_dialog',
        'plc_tools.gui.tabs',
        'plc_tools.gui.tabs.diagnostics',
        'plc_tools.gui.tabs.fault_log',
        'plc_tools.gui.tabs.io_status',
        'plc_tools.gui.tabs.program_view',
        'plc_tools.gui.tabs.tag_list',
        'plc_tools.gui.tabs.tag_monitor',
        'plc_tools.gui.widgets',
        'plc_tools.gui.widgets.status_led',
        'plc_tools.gui.widgets.tag_browser',
        'plc_tools.gui.widgets.connection_bar',
        'plc_tools.gui.widgets.recording_bar',
        'plc_tools.polling',
        'plc_tools.polling.poller',
        'plc_tools.polling.scheduler',
        'plc_tools.recording',
        'plc_tools.recording.recorder',
        'plc_tools.reports',
        'plc_tools.reports.generator',
        'pycomm3',
        'texttable',
        'xml.etree.ElementTree',
        'PySide6.QtWidgets',
        'PySide6.QtCore',
        'PySide6.QtGui',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='PLCTools',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,      # GUI app — no console window
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
